[project]
name = "locness-ph"
version = "0.1.0"
description = "Read data from MBARI mFET pH sensor. Stores data in a csv file and sqlite3 DB."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "isfetphcalc",
    "numpy>=2.3.1",
    "pyserial>=3.5",
    "pyyaml>=6.0.2",
]

[tool.uv.sources]
isfetphcalc = { git = "https://github.com/blongworth/isfetphcalc.git" }

[project.scripts]
ph = "read_ph_sensor:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
